name: desafio-ci
on:
  pull_request:
    branches:
      - main

jobs:
  valida-aplicacao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test --coverage

      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: brunogomes99/desafio-ci-node:latest

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

